// ==========================================
// CHRONOTOMI WEALTH - WATCH COLLECTION
// ==========================================
// To add a new watch:
// 1. Copy one of the existing blocks { ... } below.
// 2. Paste it into the list (make sure there is a comma after the previous block).
// 3. Update the details and image path.
// 
// To remove a watch:
// 1. Delete its corresponding block { ... }, from the list.
// 
// Note: Ensure the 'image' property matches a file in the "assets/" folder.
// ==========================================

let watches = [
  {
    brand: "Rolex",
    model: "Submariner Date",
    reference: "126613LB",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/Submariner-Date-Blue-Ceramic-Oyster-41mm-Oystersteel-And-Yellow-Gold.png",
  },
  {
    brand: "Patek Philippe",
    model: "Nautilus",
    reference: "5811/1G-001",
    set: "Box + Papers",
    caseSize: "41mm",
    image: "assets/gen_patek_1_1776373728459.png",
  },
  {
    brand: "Audemars Piguet",
    model: "Royal Oak",
    reference: "15510ST.OO.1320ST.06",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/royal-oak-41mm-15510ST.OO.1320ST.06.png",
  },
  {
    brand: "Cartier",
    model: "Santos de Cartier",
    reference: "WSSA0071",
    set: "Full Set",
    caseSize: "Large",
    image: "assets/santos-de-cartier-large-WSSA0071.png",
  },
  {
    brand: "Rolex",
    model: "GMT-Master II",
    reference: "126710GRNR",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/GMT-Master-II-126710GRNR.png",
  },
  {
    brand: "Patek Philippe",
    model: "Aquanaut",
    reference: "5167A-001",
    set: "Box + Papers",
    caseSize: "40.8mm",
    image: "assets/patek-phillipe-aquanaut-5167A-001.png",
  },
  {
    brand: "Rolex",
    model: "Yacht-Master II",
    reference: "126680",
    set: "Full Set",
    caseSize: "44mm",
    image: "assets/yacht-master-II-Oyster-44mm-Oystersteel-Reference-126680.png?v=2",
  },
  {
    brand: "Patek Philippe",
    model: "Calatrava",
    reference: "6119R-001",
    set: "Full Set",
    caseSize: "39mm",
    image: "assets/patek-phillipe-calatrava-6119R-001.png",
  },
  {
    brand: "Rolex",
    model: "Cosmograph Daytona",
    reference: "126519LN",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/cosmograph-daytona-oyster-40mm-white-gold-126519LN.jpeg",
  },
  {
    brand: "Rolex",
    model: "Datejust 41",
    reference: "126334",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/datejust-41-oyster-41mm-oystersteel-and-white-gold-126334.jpeg",
  },
  {
    brand: "Rolex",
    model: "Day-Date 40",
    reference: "228235",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/day-date-40-oyster-40mm-everose-gold-228235.jpeg",
  },
  {
    brand: "Rolex",
    model: "GMT-Master II",
    reference: "126710GRNR",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/gmt-master-II-bruce-wayne-oyster-40mm-oystersteel-126710GRNR.png",
  },
  {
    brand: "Patek Philippe",
    model: "Grand Complications",
    reference: "5270P-017",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/patek-phillipe-grand-complications-41mm-5270P-017.png",
  },
  {
    brand: "Audemars Piguet",
    model: "Royal Oak Chronograph",
    reference: "26240ST.OO.1320ST.05",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/royal-oak-chronograph-41mm-stainless-steel-26240ST.OO.1320ST.05.png",
  },
  {
    brand: "Rolex",
    model: "Yacht-Master 42",
    reference: "226658",
    set: "Full Set",
    caseSize: "42mm",
    image: "assets/yacht-master-42-oyster-42mm-yellow-gold-226658.jpeg",
  },
  {
    brand: "Rolex",
    model: "Cosmograph Daytona",
    reference: "126500LN",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/cosmograph-daytona-40mm-oystersteel-126500LN.png",
  },
  {
    brand: "Rolex",
    model: "Datejust 36",
    reference: "126234",
    set: "Full Set",
    caseSize: "36mm",
    image: "assets/datejust-36-oyster-36mm-oystersteel-and-white-gold-126234.jpeg",
  },
  {
    brand: "Rolex",
    model: "GMT-Master II",
    reference: "126710BLNR",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/gmt-master-II-oyster-40mm-oystersteel-126710BLNR.png",
  },
  {
    brand: "Rolex",
    model: "GMT-Master II",
    reference: "126718GRNR",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/gmt-master-ll-oyster-40mm-yellow-gold-126718GRNR.png",
  },
  {
    brand: "Rolex",
    model: "Perpetual 41",
    reference: "134300",
    set: "Full Set",
    caseSize: "41mm",
    image: "assets/oyster-perpetual-41-oyster-41mm-oystersteel-134300.jpeg",
  },
  {
    brand: "Cartier",
    model: "Santos de Cartier",
    reference: "WSSA0018",
    set: "Full Set",
    caseSize: "Large",
    image: "assets/santos-de-cartier-large-WSSA0018.jpeg",
  },
  {
    brand: "Rolex",
    model: "Land-Dweller",
    reference: "127334",
    set: "Full Set",
    caseSize: "40mm",
    image: "assets/rolex-land-dweller-40-40mm-127334.jpeg",
  },
  {
    brand: "Rolex",
    model: "Sky-Dweller",
    reference: "336934",
    set: "Full Set",
    caseSize: "42mm",
    image: "assets/rolex-sky-dweller-42mm-336934.webp",
  },
  {
    brand: "Cartier",
    model: "Santos de Cartier",
    reference: "WSSA0062",
    set: "Full Set",
    caseSize: "Large",
    image: "assets/santos-de-cartier-large-WSSA0062.png",
  },
  {
    brand: "Cartier",
    model: "Santos de Cartier",
    reference: "WSSA0096",
    set: "Full Set",
    caseSize: "Large",
    image: "assets/santos-de-cartier-large-WSSA0096.png",
  }
];
